[package]
name = "binarytoascii"
version = "0.1.0"
authors = ["Jurij Cerar <jurij.cerar@student.um.si>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
